blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/openhab/openhab-ios/discussions/new?category_id=27710982
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/openhab/openhab-ios/discussions/new?category_id=27710981
    about: Ask the community for help
